#!/usr/bin/env ruby
#
# y2sco: reads a yaml spatial configuration and transforms
#        it into a csound score with proper coordinates
#

require File.expand_path(File.join(['..'] * 2, 'lib', 'y2sco'), __FILE__)

if (ARGV.size < 1)
  abort("Usage: #{$0} YAML_FILE")
end

Cosb::Y2Sco::Generator.new(ARGV[0]).print

exit(0)
